[en]
  title = "Hugo Zzo Theme"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[ch]
  title = "Hugo Zzo Theme"
  languageName = "Chinese"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/ch"
