[en]
  title = "alEx's blOg # _"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[zh]
  title = "alEx's blOg # _"
  languageName = "中文"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/zh"
