[en]
  title = "alEx's blOg # _"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[cn]
  title = "alEx's blOg # _"
  languageName = "Chinese"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/cn"
