[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 4

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "画廊"
  url = "gallery"
  weight = 2

[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 1