[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 4

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 3

# [[main]]
#   identifier = "presentation"
#   name = "Pt"
#   url = "presentation"
#   weight = 3

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 2
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"

[[main]]
  parent = "gallery"
  name = "Street Artisc"
  url = "gallery/street_artisc"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1

# [[main]]
#   identifier = "showcase"
#   name = "Showcase"
#   url = "showcase"
#   weight = 6