baseurl = "https://baddate.top"
languageCode = "en-us"
paginate = 10

rssLimit = 20

enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = true




[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.en]
    title = "alEx's blOg"
    subtitle = "The most incomprehensible thing about the world is that it is at all comprehensible."
    #这世界最費解的，是它竟可被理解。
    keywords = ""
    email = "badgatex@outlook.com"
    copyright = "created by alex"
  [author]
    name = "Alex"
    email = "badgatex@outlook.com"