baseurl = "https://baddate.xyz"
languageCode = "en-us"
theme = "terminal"
paginate = 8

enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = true
[params]


  favicon = "/static/img/favicon/icon2.svg"
  author = "Alex"
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.en]
    title = "alEx"
    subtitle = "The most incomprehensible thing about the world is that it is at all comprehensible."
    #这世界最費解的，是它竟可被理解。
    keywords = ""
    copyright = "©2019 made by alex"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "bAdDatE"
      logoHomeLink = "/"

    # [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "email"
        name = "Email"
        url = "mailto:alex.ra.code@gmail.com"
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/Alex_Hans"
